### ISSUE TITLE
Syntax error line 130

### ISSUE THREAD

**Issue by Chelsea486MHz** [skywind3000/Intel2GAS#1]
I'm trying to translate NASM sources to GAS ones, being too lazy to do it myself or to write a script for it I found this one, however it doesn't seem to work and my Python knowledge is not good enough to allow me to fix it by myself.

**Comment by bencz** [comment]
I have exactly the same problem:

```
  File "intel2gui.pyw", line 130
    print 'Input => "%s"' % variable.get()      # get from var
                        ^
SyntaxError: invalid syntax
```

**Comment by skywind3000** [comment]
can you give me the sample code

**Comment by bencz** [comment]
Hi :)
There is no sample code, I just execute the command to open the intel2gas 

> $ python intel2gui.pyw

**Comment by skywind3000** [comment]
which python version are you using ？
2？3？

**Comment by bencz** [comment]
Python 3

**Comment by Chelsea486MHz** [comment]
I am using Python 3.

**Comment by Chelsea486MHz** [comment]
Fixed by using Python 2.
